### ISSUE TITLE
use of 'xhr' and 'myRequest'

### ISSUE THREAD

**Issue by JMurphyWeb** [lucymonie/api-workshop#15]
In https://github.com/lucymonie/api-workshop/blob/master/03-xmlhttprequest.md the example stores the xhr object in a variable called 'myRequest'

I think it is useful to keep it consistent in this first intro, I would suggest using 'var xhr = ...' throughout this (great) tutorial 🌮

**Comment by lucymonie** [comment]
Good point @JMurphyWeb, I will change it. Thanks!
