### ISSUE TITLE
New readme for http

### ISSUE THREAD

**Issue by lucymonie** [lucymonie/api-workshop#5]
@skibinska I think we need a separate readme for http so we can discuss http methods and status codes properly. Are you okay with that?

**Comment by skibinska** [comment]
yeap, I actually mentioned it in my workshop, but it makes more to introduce it here.
Should we rethink the way that we will be presenting this workshop or won't ask the questions about this topic?

**Comment by lucymonie** [comment]
I just added some questions! What about JSON? Should we add something about that too?

**Comment by skibinska** [comment]
I would just add to first readme  one sentence about JSON  - it *is a way to store information in an organized, easy-to-access manner* and maybe that it looks like a JS object but its keys and values are in quotation mark.
